import Head from 'next/head'
import Cart from '../components/Cart'
import Grid from '../components/Grid'
import Header from '../components/Header'
import Navbar from '../components/Navbar'



export default function Home() {
  return (
    <div className="
      h-screen 
    bg-gray-100
      overflow-hidden">

      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />

      <main className="flex">
        <Navbar />
        <Grid />
        <Cart />
      </main>
      
    </div>
  )
}
