import Head from "next/head";
import Cart from "../components/Cart";
import Grid from "../components/Grid";
import Header from "../components/Header";
import Nav from "../components/Nav";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div
      className="
      h-screen
      overflow-hidden
      "
    >
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />

      <main className="flex">
        <Nav />
        <Grid results={results} />
        <Cart />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const category = context.query.category;

  const request = await fetch(
    `https://my-json-server.typicode.com/aswin-remesan/food_pos_api/${
      requests[category]?.url || requests.Mains.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request,
    },
  };
}
